name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  BUILD_SCRIPT: ManaReg.vm
  RELEASE_FILE: ManaReg.vdf

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set tag and directory name env
        run: |
          export tagName=${GITHUB_REF/refs\/tags\//}
          echo "Tag: ${tagName}"
          echo "RELEASE_VERSION=${tagName}" >> $GITHUB_ENV

      - name: Package VDF
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          curl --output ./vdfsbuilder https://github.com/kirides/vdfsbuilder/releases/download/v1.0.0/vdfsbuilder.linux-amd64
          chmod +x ./vdfsbuilder
          ls -R
          ./vdfsbuilder \
            -b ${{ env.GITHUB_WORKSPACE }} \
            -o ./${{ env.RELEASE_FILE }} \
            ./${{ env.BUILD_SCRIPT }}

      - name: Calculate distribution hash
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          sha256sum "$RELEASE_FILE" > "$RELEASE_FILE.sha256"
          cat "$RELEASE_FILE.sha256"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            ${{ env.RELEASE_FILE }}
            ${{ env.RELEASE_FILE }}.sha256

      - name: Create github release
        run: |
          gh release create $RELEASE_VERSION -n "Generated release from GitHub Actions"
          exit 0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload artifacts to github release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          gh release upload $RELEASE_VERSION "$RELEASE_FILE"
          gh release upload $RELEASE_VERSION "$RELEASE_FILE.sha256"
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
