name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  BUILD_SCRIPT: ManaReg.vm
  RELEASE_FILE: ManaReg.vdf

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: export RELEASE_VERSION
        run: |
          export tagName=${GITHUB_REF/refs\/tags\//}
          echo "Tag: ${tagName}"
          echo "RELEASE_VERSION=${tagName}" >> $GITHUB_ENV

      - name: Package VDF
        uses: kirides/vdfsbuilder@f6402aa7c633f4f657bc67e22efe2f0e3caa6802
        with:
          in: ${{ env.BUILD_SCRIPT }}
          out: ${{ env.RELEASE_FILE }}

      - name: Calculate distribution hash
        run: |
          sha256sum "$RELEASE_FILE" > "$RELEASE_FILE.sha256"
          cat "$RELEASE_FILE.sha256"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            ${{ env.RELEASE_FILE }}
            ${{ env.RELEASE_FILE }}.sha256

      - name: Create github release
        run: |
          gh release create $RELEASE_VERSION --generate-notes "$RELEASE_FILE" "$RELEASE_FILE.sha256"
          exit 0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
